version: '3.7'

networks:
  extnet:
    name: my-external-net

services:

  # see: https://github.com/Fmstrat/samba-domain
  samba:
    image: nowsci/samba-domain
    container_name: samba
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      - ${CONF_DIR}/samba/data/:/var/lib/samba
      - ${CONF_DIR}/samba/config/samba:/etc/samba/external
    environment:
      - DOMAIN=EHW2018.LOCAL
      - DOMAINPASS=${AD_DOMAIN_PASSWORD}
      - JOIN=false
      - INSECURELDAP:true
      #- DNSFORWARDER=${EXT_DNS_ADDR}
    networks:
      - extnet
    ports:
      - ${ADS_ADDR}:53:53
      - ${ADS_ADDR}:53:53/udp
      - ${ADS_ADDR}:88:88
      - ${ADS_ADDR}:88:88/udp
      - ${ADS_ADDR}:135:135
      - ${ADS_ADDR}:137-138:137-138/udp
      - ${ADS_ADDR}:139:139
      - ${ADS_ADDR}:389:389
      - ${ADS_ADDR}:389:389/udp
      - ${ADS_ADDR}:445:445
      - ${ADS_ADDR}:464:464
      - ${ADS_ADDR}:464:464/udp
      - ${ADS_ADDR}:636:636
      - ${ADS_ADDR}:1024-1044:1024-1044
      - ${ADS_ADDR}:3268-3269:3268-3269
    dns_search:
      - ehw2018.local
    dns:
      - ${ADS_ADDR}
      #- ${EXT_DNS_ADDR}
    extra_hosts:
      - localdc.ehw2018.local:${ADS_ADDR}
    hostname: localdc
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    privileged: true
    restart: always

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.ehw2018.local'
    #environment:
      #GITLAB_OMNIBUS_CONFIG: |
      #  external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    networks:
      - extnet
    ports:
      - "${GITLAB_ADDR}:80:80"
      - "${GITLAB_ADDR}:443:443"
      - "${GITLAB_ADDR}:10022:22"
    volumes:
      - '${CONF_DIR}/gitlab/config:/etc/gitlab'
      - '${CONF_DIR}/gitlab/logs:/var/log/gitlab'
      - '${CONF_DIR}/gitlab/data:/var/opt/gitlab'
    links:
      - samba

  jenkins:
    image: 'jenkins/jenkins:lts'
    networks:
      - extnet
    ports:
      - "${JENKINS_ADDR}:8080:8080"
    volumes:
      - '${CONF_DIR}/jenkins/data:/var/jenkins_home'
    links:
      - samba
